app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from transactions.views import HomePage

urlpatterns = [
    path('', HomePage.as_view()),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('accounts.urls')),
    path('captcha/', include('captcha.urls')),
    path('profile/', include('profiles.urls')),
]


handler404 = "app.views.page_not_found_view"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='transactions_home'),
    path('transaction/<int:pk>/', views.TransactionDetail.as_view(), name='transaction_detail'),
    # path('transactions_type/<int:transactions_type_id>/', TransactionsByCategory.as_view(extra_context={'title': 'Какой-то тайтл'}), name='category'),
    path('accounts/<int:pk>/', views.AccountDetail.as_view(), name='account_detail'),
    path('choice_account/', views.AccountListForMakeTransaction.as_view(extra_context={'title': 'Выбор категории'}),
         name='choice_account'),
    path('choice_сategory/<int:account_id>/', views.CategoryListForMakeTransaction.as_view(extra_context={'title': 'Выбор категории'}),
         name='choice_category'),
    path('add_transaction/<int:category_id>/', views.CreateTransaction.as_view(), name='add_transaction'),
    path('add_account/', views.CreateAccount.as_view(), name='add_account'),
    path('add_transaction_type/<str:main_type>/', views.CreateTransactionType.as_view(), name='add_transaction_type'),
    path('get_xlsx_file/', views.upload_exel, name="upload_exel"),

    path('make_income_expenditure/<int:id_currency>/', views.TransactionChartAPIView.as_view(), name='make_income_expenditure'),

    path('transactions/<int:pk>/update', views.UpdateTransaction.as_view(), name='transactions_update'),
    path('transactions/<int:pk>/delete', views.DeleteTransaction.as_view(), name='transactions_delete'),

]

transactions/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from transactions.serveces.processing_tranasctions import TransactionsLogic


class Icons(models.Model):
    title = models.CharField(max_length=50, db_index=True, verbose_name="Наименование")
    file = models.CharField(max_length=50, db_index=True, verbose_name="Наименование файла")
    unicode = models.CharField(max_length=50, db_index=True, verbose_name="юникод символа")
    unicode_icons = models.CharField(max_length=50, db_index=True, verbose_name="дешифрованный юникод символа")

    def get_absolute_url(self):
        return reverse('icons', kwargs={"icons_id": self.pk})

    def __str__(self):
        return self.title + ' ' + self.unicode_icons

    class Meta:
        verbose_name = "иконка"
        verbose_name_plural = "иконки"
        ordering = ['title']


class Currency(models.Model):
    title = models.CharField(max_length=50, db_index=True, verbose_name="Наименование валюты")

    # type_id = True
    def get_absolute_url(self):
        return reverse('currency', kwargs={"currency_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Валюта"
        verbose_name_plural = "Валюты"
        ordering = ['title']


class AccountsType(models.Model):
    title = models.CharField(max_length=30, db_index=True, verbose_name="Наименование типа счётов")

    def get_absolute_url(self):
        return reverse('accounts_type', kwargs={"accounts_type_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Тип cчётов"
        verbose_name_plural = "Типы счётов"
        ordering = ['title']


class Accounts(models.Model):
    balans = models.DecimalField(verbose_name="Баланс счета", max_digits=17, decimal_places=2, blank=True)
    title = models.CharField(max_length=60, db_index=True, verbose_name="Наименование счета")
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name='Владелец счёта')
    accounts_type = models.ForeignKey(AccountsType, on_delete=models.PROTECT, null=True, verbose_name="Тип счёта")
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT, null=True, verbose_name="Валюта счёта")

    def get_absolute_url(self):
        return reverse('accounts', kwargs={"accounts_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Счёт"
        verbose_name_plural = "Cчёты"
        ordering = ['title']


class TransactionsType(models.Model):
    main_type = models.BooleanField(verbose_name="Тип:")  # False - расход | True - Доход
    category = models.CharField(max_length=60, db_index=True, verbose_name="Категория")
    icons = models.ForeignKey(Icons, on_delete=models.PROTECT, null=True, verbose_name="Иконка")
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT, null=True, verbose_name="Валюта транзакции")
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name='Владелец типа')

    def get_absolute_url(self):
        return reverse('transactions_type', kwargs={"transactions_type_id": self.pk})

    def __str__(self):
        # main_type = ''
        if self.main_type:
            main_type = "Доход"
        else:
            main_type = "Расход"
        result = main_type + ' ' + str(self.category)
        return result

    class Meta:
        verbose_name = "Тип транзакций"
        verbose_name_plural = "Типы транзакций"
        ordering = ['main_type']


class Transactions(models.Model):
    money_value = models.DecimalField(verbose_name='Денежная сумма', max_digits=17, decimal_places=2)
    comment = models.TextField(verbose_name='Примечание к транзакции', max_length=150, blank=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        verbose_name='Владелец транзакции')
    data_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата совершения транзакции")
    # currency = models.ForeignKey(Currency, on_delete=models.PROTECT, null=True, verbose_name="Валюта транзакции")
    transactions_type = models.ForeignKey(
        TransactionsType,
        on_delete=models.PROTECT,
        null=True,
        verbose_name="Тип транзакции"
    )
    accounts = models.ForeignKey(
        Accounts,
        on_delete=models.PROTECT,
        null=True,
        verbose_name="Счёт транзакции"
    )



    def get_absolute_url(self):
        return reverse('transactions', kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.money_value)

    def save(self, *args, **kwargs):
        if (self.money_value == 0) or (self.money_value < 0 and self.transactions_type.main_type == True) or (
                self.money_value > 0 and self.transactions_type.main_type == False):
            return False
        if self.transactions_type.currency != self.accounts.currency:
            return False
        super(Transactions, self).save(*args, **kwargs)
        # self.transactions_logic = TransactionsLogic(account=self.accounts, money_value=self.money_value, transactions=Transactions.objects.filter(owner=self.owner, transactions_type__currency=self.transactions_type.currency, accounts=self.accounts))
        # self.transactions_logic.update_balans()

    def delete(self, using=None, keep_parents=False):
        super(Transactions, self).delete()
        # self.transactions_logic = TransactionsLogic(account=self.accounts, money_value=self.money_value, transactions=Transactions.objects.filter(owner=self.owner, transactions_type__currency=self.transactions_type.currency, accounts=self.accounts))
        # self.transactions_logic.update_balans()

    class Meta:
        verbose_name = "Транзакция"
        verbose_name_plural = "Транзакции"
        ordering = ['-data_time']

transactions/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Transactions, Accounts, TransactionsType
from transactions.fields import MoneyField


class TransactionFrom(forms.ModelForm):
    money_value = MoneyField(widget=forms.TextInput(attrs={'class': 'form-control money_input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['accounts'].empty_label = "Счет транзакции не выбран"
        self.fields['transactions_type'].empty_label = "категория транзакции не выбрана"

    def clean(self):
        money_value = self.cleaned_data['money_value']
        transactions_type = self.cleaned_data['transactions_type']
        if money_value < 0 and transactions_type.main_type == True:
            raise ValidationError("В доходе не может быть отрицательное число")
        elif money_value > 0 and transactions_type.main_type == False:
            raise ValidationError("В расходе не может быть положительное число")
        elif money_value == 0:
            raise ValidationError("Я не буду сохранять транзакцию с нулём...")
        return self.cleaned_data

    class Meta:
        model = Transactions
        fields = ['money_value', 'comment', 'transactions_type', 'accounts']
        widgets = {
            # 'money_value': forms.TextInput(attrs={'class': 'form-control money_input'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'rows': 5}),
            'transactions_type': forms.Select(attrs={'class': 'form-control money_input'}),
            'accounts': forms.Select(attrs={'class': 'form-control'})
        }


class AccountForm(forms.ModelForm):
    balans = MoneyField(widget=forms.TextInput(attrs={'class': 'form-control money_input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['accounts_type'].empty_label = "Тип не выбран"
        self.fields['currency'].empty_label = "Валюта не выбрана"

    class Meta:
        model = Accounts
        fields = ['title', 'balans', 'accounts_type', 'currency']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'rows': 5, 'verbose_name': "Красава молодец"}),
            'balans': forms.TextInput(attrs={'class': 'form-control money_input'}),
            'accounts_type': forms.Select(attrs={'class': 'form-control'}),
            'currency': forms.Select(attrs={'class': 'form-control'}),
        }


class TransactionTypeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['currency'].empty_label = "Валюта категории не выбрана"

    class Meta:
        model = TransactionsType
        fields = ['category', 'currency', 'icons']
        widgets = {

            'main_type': forms.CheckboxInput(attrs={'class': 'main_type'}),
            'category': forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),
            'currency': forms.Select(attrs={'class': 'form-control'}),
            'icons': forms.Select(attrs={'class': 'form-control'})
        }

templates/transactions/account_detail.html
{% extends 'base.html' %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% block content %}
    <div class="flex-col card my-chadow my-margin my-padding">
        <h1>{{ account.title }}</h1>
        <div class="p-1">
            <p>Баланс: <b>{{ account.currency }} {{ account.balans }}</b></p>
            <p>Тип: {{ account.accounts_type.title }}</p>
        </div>
    </div>

{% endblock %}

templates/transactions/account_list_for_make_transaction.html
{% extends 'base.html' %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% block content %}
    <div class="flex-col p-2 m-2" style="margin: 15px; width: 100%">
        <h4>Выберите счёт</h4>
        {{ mixin_prop }}
        <div class="d-flex flex-col card p-3 my-chadow" style="margin: 15px;">

            {% for account in accounts %}

                <div class="d-flex flex-row transaction_type align-items-center">
                    <div class="d-flex align-items-center my-padding">
                    </div>
                    <div href="{% url 'choice_category' account.pk %}" class="d-flex mb-1">
                        <a type="a" href="{% url 'choice_category' account.pk %}"
                           class="btn btn-outline-primary transaction_type__button"><b>{{ account.title }}</b> {{ account.category }}
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/transactions/add_account.html
{% extends 'base.html' %}

{% comment %}
{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}
{% endcomment %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% block content %}


    <div class="flex-col card my-chadow my-padding" style="margin: 15px">
        <h1>Добавление счёта</h1>
        <div class="p-3">
            <form action="{% url 'add_account' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary btn-block">Добавить счёт</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/transactions/add_transactions.html
{% extends 'base.html' %}

{% comment %}
{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}
{% endcomment %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% block content %}

    <div class="flex-col card box-shadow:0 1px 15px darkgrey my-padding my-chadow" style="margin: 15px">
        <h1>Добавление транзакции</h1>

        <div class="p-3">
            <form action="{% url 'add_transaction' category.pk %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary btn-block">Добавить запись</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/transactions/add_transactions_type.html
{% extends 'base.html' %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% block content %}
    <div class="flex-col card my-chadow my-margin my-padding">
        <h1>Добавление категориииии
            {% if main_type == "True" %}
                Дохода
            {% else %}
                Расхода
            {% endif %}
        </h1>
        <div class="p-3">
            <form action="{% url 'add_transaction_type' main_type %}" method="post">
                <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
                      rel="stylesheet"/>
                {% csrf_token %}
                {{ form.as_p }}


                {#                    <p>#}
                {#                        <label for="id_icons">Иконка:</label>#}
                {#                        <select name="icons" required="" id="id_icons">#}
                {#                            <option value="" selected="">---------</option>#}
                {#                            <option value="14">Горячая чашка&amp;#xf0f4;</option>#}
                {#                            <option value="21">Деньги в руке---</option>#}
                {#                            <option value="15">Кинопленка&amp;#xf008;</option>#}
                {#                            <option value="13">Корзинка&amp;#xf291;</option>#}
                {#                            <option value="18">Люди#xf0c0;</option>#}
                {#                            <option value="19">Магазин---</option>#}
                {#                            <option value="20">Подарок#xf06b;</option>#}
                {#                            <option value="23">Портфель#xf0b1;</option>#}
                {#                            <option value="17">Сердце#xf004;</option>#}
                {#                            <option value="16">Транспорт#xf1b9;</option>#}
                {#                            <option value="22">Человек с монетой---</option>#}
                {#                        </select>#}
                {#                    </p>#}


                <button type="submit" class="btn btn-primary btn-block">Добавить тип транзакции</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/transactions/category_list_for_make_transaction.html
{% extends 'base.html' %}

{% comment %}
{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}
{% endcomment %}
{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% load money_tags %}


{% block content %}
    <div class="flex-col p-2 m-2" style="margin: 15px; width: 100%">
        <h4>Выбери категорию</h4>
        {{ mixin_prop }}
        <div class="d-flex flex-col card p-3 my-chadow" style="margin: 15px;">
            <h3>Доходы</h3>


            {% for income in income %}

                <div class="d-flex flex-row transaction_type align-items-center">
                    <div class="d-flex align-items-center my-padding">
                        <img src="/static/bootstrap-icons-1.9.1/{{ income.icons.file }}.svg"
                             width="30" height="30" class="d-inline-block align-top" alt="">
                    </div>
                    <div href="{% url 'add_transaction' income.pk %}" class="d-flex mb-1">
                        <a type="a" href="{% url 'add_transaction' income.pk %}"
                           class="btn btn-outline-primary transaction_type__button"><b>{{ income.currency }}</b> {{ income.category }}</a>
                    </div>
                </div>
            {% endfor %}
            <div href="" class="d-flex card mb-1">
                <a type="a" href="{% url 'add_transaction_type' 'True' %}" class="btn btn-outline-primary">+</a>
            </div>
        </div>

        <div class="d-flex flex-col card p-3 my-chadow" style="margin: 15px;">
            <h3>Расходы</h3>
            {% for expenditure in expenditure %}
               <div class="d-flex flex-row transaction_type align-items-center">
                    <div class="d-flex align-items-center my-padding">
                        <img src="/static/bootstrap-icons-1.9.1/{{ expenditure.icons.file }}.svg"
                             width="30" height="30" class="d-inline-block align-top" alt="">
                    </div>
                    <div href="{% url 'add_transaction' expenditure.pk %}" class="d-flex mb-1">
                        <a type="a" href="{% url 'add_transaction' expenditure.pk %}"
                           class="btn btn-outline-primary transaction_type__button"><b>{{ expenditure.currency }}</b> {{ expenditure.category }}</a>
                    </div>
                </div>
            {% endfor %}
            <div href="" class="d-flex card mb-1">
                <a type="a" href="{% url 'add_transaction_type' 'False' %}" class="btn btn-outline-primary">+</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/transactions/home_transactions_list.html
{% extends 'base.html' %}

{% comment %}
{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}
{% endcomment %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% load money_tags %}
{% load static %}
{% block main %}




    <div class="card my-margin my-padding my-chadow" id="container">
    <div class="d-flex flex-row justify-content-center">
        {% for currency in currency %}
            <button id="button_income_expenditure" class="button_income_expenditure btn btn-secondary" value="{{ currency.pk }}" style="margin: 5px; width: 100px">{{ currency.title }}</button>
        {% endfor %}
    </div>
        {#    <canvas id="pie-chart"></canvas>#}
        <h5 class="d-flex justify-content-center"><b>{{ month|date:'F' }}</b></h5>
        <canvas id="speedChart" style="width: 100%; height: 250px;"></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script type="text/javascript" src="{% static 'js_chart/income_expenditure.js' %}" defer></script>


{% endblock %}

{% block content %}
    <div class="card my-chadow my-margin">
        <div class="my-padding">
            <h3>История транзакций</h3>
        </div>
        {{ mixin_prop }}

        {% if transactions == NULL %}
            <h6>transactions == NULL</h6>
        {% else %}
            <div class="">


                {% for item in transactions %}
                    {% ifchanged item.data_time|date:"dm" %}

                        <div class="d-flex justify-content-center transaction-time">
                            <p><b>{{ item.data_time|date:"d.m, D" }}</b></p>
                        </div>
                    {% endifchanged %}



                    {% if item.transactions_type.main_type %}
                        <div class="d-flex flex-row transaction justify-content-between transaction p-1 transaction__bg-green">
                            <div class="d-flex align-items-center my-padding">
                                <img src="/static/bootstrap-icons-1.9.1/{{ item.transactions_type.icons.file }}.svg"
                                     width="30" height="30" class="d-inline-block align-top" alt="">
                            </div>
                            <div class="d-flex flex-column align-items-center transaction__right_info">
                                <div class="d-flex">
                                    <a href="{% url 'transaction_detail' item.pk %}">
                                        <h5>{{ item.transactions_type.currency }} {{ item.money_value|money_filter }}</h5>
                                    </a>
                                </div>
                                <div class="d-flex">
                                    <p>{{ item.accounts }}</p>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="d-flex flex-row transaction justify-content-between p-1 transaction__bg-red">
                            <div class="d-flex align-items-center my-padding">
                                <img src="/static/bootstrap-icons-1.9.1/{{ item.transactions_type.icons.file }}.svg"
                                     width="30" height="30" class="d-inline-block align-top" alt="">
                            </div>
                            <div class="d-flex flex-column align-items-center transaction__right_info">
                                <div class="d-flex">
                                    <a href="{% url 'transaction_detail' item.pk %}">
                                        <h5>{{ item.accounts.currency }} {{ item.money_value|money_filter }}</h5>
                                    </a>
                                </div>
                                <div class="d-flex">
                                    <p>{{ item.accounts }}</p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <div class="transaction my-margin">
                        <h6 class="text-secondary">Туть пусто.</h6>
                    </div>
                {% endfor %}
                {#                <div class="transaction-time"></div>#}
            </div>
        {% endif %}


    </div>

{% endblock %}

{% block bonus_inf %}
    {% include 'transaction includes/make_transactions_sidebar.html' %}
{% endblock %}

templates/transactions/transaction_delete.html
{% extends 'base.html' %}
{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block content %}
    <div class="flex-col card my-chadow my-margin my-padding">
        <h1>Удаление транзакции</h1>
        <div class="p-1">

            <form method="POST">
                {% csrf_token %}
                <p>Вы уверены, что хотите удалить?</p>
                <button type="submit" class="btn btn-danger btn-block">Удалить</button>

            </form>


        </div>
    </div>

{% endblock %}

templates/transactions/transaction_update.html
{% extends 'base.html' %}
{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block content %}
    <div class="flex-col card my-chadow my-margin my-padding">
        <h1>Редактирование транзакции</h1>
        <div class="p-1">


            <p>
                {% if  transactions.transactions_type.main_type %}
                    Доход:
                {% else %}
                    Расход:
                {% endif %}
                <b>{{ transactions.transactions_type.category }}</b></p>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-primary btn-block">Сохранить</button>

            </form>


        </div>
    </div>

{% endblock %}

templates/transactions/transactions_detail.html
{% extends 'base.html' %}

{% block profile %}
    {% include 'inc/_profile.html' %}
{% endblock %}

{% block menu %}
    {% include 'transaction includes/profile_finances_sidebar.html' %}
{% endblock %}

{% block content %}
    <div class="flex-col card my-chadow my-margin my-padding">
        <h1>Детали транзакции</h1>
        <div class="p-1">
            <p>

                {% if  transaction_one.transactions_type.main_type %}
                    Доход:
                {% else %}
                    Расход:
                {% endif %}
                <b>{{ transaction_one.transactions_type.category }}</b></p>
            <p>Сумма: <b>{{ transaction_one.transactions_type.currency }} {{ transaction_one.money_value }}</b></p>
            <p class="text-justify transaction-card__comment_text">Примечание: {{ transaction_one.comment }}</p>
            <p>Время добавления: {{ transaction_one.data_time }}</p>
            <p>Cчёт транзакции: <b>{{ transaction_one.accounts.title }}</b></p>
            <p><a href="{% url 'transactions_update' transaction_one.id %}"
                  class="btn btn-primary btn-block">Редактировать</a></p>
            <p><a href="{% url 'transactions_delete' transaction_one.id %}" class="btn btn-danger btn-block">Удалить</a>
            </p>
        </div>
    </div>






{% endblock %}

templates/transactions/xlsx_file.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "upload_exel" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>